Repository Novik/ruTorrent, pull requests merged in 2022-12, with the labels that each got.

#2388 Support additional parameters in addtorrent.php
  php/addtorrent.php
Labels: enhancement, Priority-Medium, v4.0 - Stable

#2395 Plugin: check_port fix for portchecker.co
  plugins/check_port/action.php
Labels: bug, Priority-Critical, v4.0 - Stable

#2425 Fix & Sanitize RSS HTML Tags
  plugins/rss/init.js
Labels: bug, Priority-Critical, WIP, v4.0 - Stable
