Repository Novik/ruTorrent, pull requests merged in 2023-01, with the labels that each got.

#2394 Improve table sorting
  js/stable.js
  js/webui.js
  plugins/_task/init.js
  plugins/extsearch/init.js
  plugins/geoip/init.js
  plugins/history/init.js
  plugins/rss/init.js
  plugins/tracklabels/init.js
Labels: bug, Priority-High, v4.0 - Stable

#2396 Use Ipv4 address for port checker
  php/Snoopy.class.inc
  plugins/check_port/action.php
  plugins/check_port/conf.php
Labels: bug, enhancement, Priority-Medium, v4.0 - Stable

#2404 RSS parsing with libxml
  php/utility/utility.php
  plugins/rss/rss.php
  plugins/rss/rss_reader.php
  tests/Readme.md
  tests/php-test.ini
  tests/php-test.sh
  tests/php/TestCase.php
  tests/plugins/rss/RSSTest.php
  tests/plugins/rss/atom-sample.xml
  tests/plugins/rss/rss-jp-sample.xml
  tests/plugins/rss/rss-sample-erroneous.xml
Labels: bug, enhancement, Priority-Low, v4.1

#2393 Multi select labels
  js/stable.js
  js/webui.js
  plugins/extsearch/init.js
  plugins/rss/init.js
  plugins/tracklabels/init.js
Labels: enhancement, Priority-Low, v4.1

#2428 Add bbcode support in rss description
  index.html
  plugins/rss/init.js
  plugins/rss/rss.css
  tests/plugins/rss/init.spec.js
Labels: enhancement, Priority-Medium, WIP, v4.1
