Repository Novik/ruTorrent, pull requests merged in 2024-12, with the labels that each got.

#2812 Use flex layout on context menu items
  css/style.css
  images/menuexp.gif
  images/menusel.gif
  js/objects.js
  js/webui.js
  plugins/theme/themes/Acid/images/menuexp.gif
  plugins/theme/themes/Acid/images/menusel.gif
  plugins/theme/themes/Acid/style.css
  plugins/theme/themes/Blue/images/menu-parent.gif
  plugins/theme/themes/Blue/style.css
  plugins/theme/themes/Dark/images/menuexp.gif
  plugins/theme/themes/Dark/images/menusel.gif
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/images/menuexp.svg
  plugins/theme/themes/DarkBetter/images/menusel.svg
  plugins/theme/themes/DarkBetter/style.css
  plugins/theme/themes/Excel/style.css
  plugins/theme/themes/MaterialDesign/images/menus.png
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/images/menus.png
  plugins/theme/themes/Oblivion/style.css
Labels: enhancement, v5.2

#2813 Adjust status bar and top menu
  css/style.css
  index.html
  js/objects.js
  js/webui.js
  plugins/theme/themes/Acid/style.css
  plugins/theme/themes/Blue/style.css
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/style.css
  plugins/theme/themes/Excel/images/statbg.png
  plugins/theme/themes/Excel/style.css
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/style.css
Labels: bug, v5.2, cleanup

#2815 Define dialog window colors using variables
  css/style.css
  plugins/rss/rss.css
  plugins/theme/themes/Acid/style.css
  plugins/theme/themes/Blue/style.css
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/style.css
  plugins/theme/themes/Excel/style.css
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/style.css
Labels: v5.2, cleanup

#2820 Fix top menu collapsing issue
  css/style.css
  index.html
  js/objects.js
  js/webui.js
Labels: bug, v5.1

#2826 Distribute WebUi space using flex layout
  css/style.css
  index.html
  js/webui.js
  plugins/trafic/init.js
Labels: bug, Priority-High, Confirmed, v5.1, v5.2

#2827 Various bug fixes for v5.1
  css/style.css
  js/content.js
  plugins/check_port/init.js
  plugins/trafic/init.js
Labels: bug, Priority-High, Confirmed, v5.1

#2825 Remove Internet Explorer support, and some useragent sniffing hacks
  css/stable.css
  css/style.css
  js/browser.js
  js/plugins.js
  js/stable.js
  plugins/_getdir/init.js
  plugins/extratio/ie.css
  plugins/extsearch/init.js
  plugins/rss/ie.css
  plugins/rss/init.js
  plugins/rssurlrewrite/ie.css
  plugins/rssurlrewrite/init.js
  plugins/theme/themes/Dark/stable.css
  plugins/theme/themes/DarkBetter/stable.css
  plugins/theme/themes/MaterialDesign/stable.css
  plugins/theme/themes/Oblivion/stable.css
Labels: v5.2, cleanup

#2821 Change various s-table methods
  css/stable.css
  css/style.css
  js/stable.js
  plugins/extsearch/init.js
  plugins/theme/themes/DarkBetter/style.css
Labels: enhancement, v5.2

#2833 Define status bar icons using base64 strings
  css/style.css
  images/status_down.gif
  images/status_up.gif
  plugins/check_port/check_port.css
  plugins/check_port/images/green.png
  plugins/check_port/images/red.png
  plugins/check_port/images/yellow.png
  plugins/check_port/init.js
  plugins/cpuload/cpuload.css
  plugins/cpuload/images/cpu.png
  plugins/diskspace/diskspace.css
  plugins/diskspace/images/disk.png
  plugins/theme/themes/Acid/images/disk.gif
  plugins/theme/themes/Acid/images/status_down.gif
  plugins/theme/themes/Acid/images/status_up.gif
  plugins/theme/themes/Acid/plugins.css
  plugins/theme/themes/Acid/style.css
  plugins/theme/themes/Blue/plugins.css
  plugins/theme/themes/Blue/style.css
  plugins/theme/themes/Dark/plugins.css
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/images/cpu.svg
  plugins/theme/themes/DarkBetter/images/disk.svg
  plugins/theme/themes/DarkBetter/images/green.svg
  plugins/theme/themes/DarkBetter/images/red.svg
  plugins/theme/themes/DarkBetter/images/yellow.svg
  plugins/theme/themes/DarkBetter/plugins.css
  plugins/theme/themes/DarkBetter/style.css
  plugins/theme/themes/Excel/plugins.css
  plugins/theme/themes/Excel/style.css
  plugins/theme/themes/MaterialDesign/images/green.png
  plugins/theme/themes/MaterialDesign/plugins.css
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/plugins.css
  plugins/theme/themes/Oblivion/style.css
Labels: enhancement, v5.2

#2831 Animate category panel
  css/category-panel.css
  css/style.css
  images/pnl_close.gif
  images/pnl_open.gif
  plugins/theme/themes/Acid/images/pnl_close.gif
  plugins/theme/themes/Acid/images/pnl_open.gif
  plugins/theme/themes/Acid/style.css
  plugins/theme/themes/Blue/images/pnl_close.gif
  plugins/theme/themes/Blue/images/pnl_open.gif
  plugins/theme/themes/Blue/style.css
  plugins/theme/themes/Dark/images/pnl_close.gif
  plugins/theme/themes/Dark/images/pnl_open.gif
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/images/pnl_close.gif
  plugins/theme/themes/DarkBetter/images/pnl_close.svg
  plugins/theme/themes/DarkBetter/images/pnl_open.gif
  plugins/theme/themes/DarkBetter/images/pnl_open.svg
  plugins/theme/themes/DarkBetter/style.css
  plugins/theme/themes/Excel/images/pnl_close.png
  plugins/theme/themes/Excel/images/pnl_open.png
  plugins/theme/themes/Excel/init.js
  plugins/theme/themes/Excel/style.css
  plugins/theme/themes/MaterialDesign/images/pnl_close.png
  plugins/theme/themes/MaterialDesign/images/pnl_open.png
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/images/pnl_close.png
  plugins/theme/themes/Oblivion/images/pnl_open.png
  plugins/theme/themes/Oblivion/style.css
Labels: enhancement, v5.2

#2830 Define getter functions on s-table
  js/stable.js
Labels: enhancement, v5.2, cleanup

#2819 Use bootstrap list group on options window
  css/style.css
  index.html
  js/common.js
  js/content.js
  js/options.js
  js/plugins.js
  plugins/_getdir/init.js
  plugins/extsearch/init.js
  plugins/theme/themes/Acid/style.css
  plugins/theme/themes/Blue/style.css
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/style.css
  plugins/theme/themes/Excel/style.css
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/style.css
Labels: enhancement, v5.2, cleanup

#2836 Define s-table header styles using variables
  css/stable.css
  css/style.css
  images/asc.gif
  images/blank.gif
  images/desc.gif
  images/header.gif
  js/stable.js
  plugins/theme/init.js
  plugins/theme/themes/Acid/images/asc.gif
  plugins/theme/themes/Acid/images/blank.gif
  plugins/theme/themes/Acid/images/desc.gif
  plugins/theme/themes/Acid/images/header.gif
  plugins/theme/themes/Acid/stable.css
  plugins/theme/themes/Acid/style.css
  plugins/theme/themes/Blue/images/asc.gif
  plugins/theme/themes/Blue/images/blank.gif
  plugins/theme/themes/Blue/images/desc.gif
  plugins/theme/themes/Blue/stable.css
  plugins/theme/themes/Dark/images/asc.gif
  plugins/theme/themes/Dark/images/blank.gif
  plugins/theme/themes/Dark/images/desc.gif
  plugins/theme/themes/Dark/images/header.gif
  plugins/theme/themes/Dark/stable.css
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/images/asc.gif
  plugins/theme/themes/DarkBetter/images/asc.svg
  plugins/theme/themes/DarkBetter/images/blank.gif
  plugins/theme/themes/DarkBetter/images/desc.gif
  plugins/theme/themes/DarkBetter/images/desc.svg
  plugins/theme/themes/DarkBetter/images/header.gif
  plugins/theme/themes/DarkBetter/stable.css
  plugins/theme/themes/Excel/images/asc.gif
  plugins/theme/themes/Excel/images/blank.gif
  plugins/theme/themes/Excel/images/desc.gif
  plugins/theme/themes/Excel/images/header.gif
  plugins/theme/themes/Excel/stable.css
  plugins/theme/themes/MaterialDesign/images/asc.gif
  plugins/theme/themes/MaterialDesign/images/desc.gif
  plugins/theme/themes/MaterialDesign/stable.css
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/images/asc.gif
  plugins/theme/themes/Oblivion/images/blank.gif
  plugins/theme/themes/Oblivion/images/desc.gif
  plugins/theme/themes/Oblivion/stable.css
Labels: enhancement, v5.2, cleanup

#2837 Improve s-table column resizing
  css/stable.css
  js/stable.js
  plugins/theme/themes/Acid/stable.css
  plugins/theme/themes/Blue/stable.css
  plugins/theme/themes/Dark/stable.css
  plugins/theme/themes/DarkBetter/stable.css
  plugins/theme/themes/Excel/stable.css
  plugins/theme/themes/MaterialDesign/stable.css
  plugins/theme/themes/Oblivion/stable.css
Labels: bug, enhancement, v5.2
