Repository Novik/ruTorrent, pull requests merged in 2024-10, with the labels that each got.

#2719 Apply flex layout to chunks tab page
  css/stable.css
  css/style.css
  index.html
  js/common.js
  js/objects.js
  plugins/chunks/chunks.css
  plugins/chunks/init.js
  plugins/datadir/datadir.css
  plugins/datadir/init.js
  plugins/rss/rss.css
  plugins/scheduler/init.js
  plugins/scheduler/scheduler.css
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/style.css
  plugins/throttle/init.js
  plugins/trafic/init.js
  plugins/unpack/init.js
Labels: bug, enhancement, v4.4

#2722 Various bug fixes for v5-beta1
  css/style.css
  index.html
  js/objects.js
  js/webui.js
  plugins/_task/_task.css
  plugins/create/create.css
  plugins/create/init.js
  plugins/spectrogram/init.js
  plugins/spectrogram/spectrogram.css
  plugins/theme/themes/Blue/images/left-corners.png
  plugins/theme/themes/Blue/images/left-right.png
  plugins/theme/themes/Blue/images/right-corners.png
  plugins/theme/themes/Blue/images/shadow-c.png
  plugins/theme/themes/Blue/images/shadow-lr.png
  plugins/theme/themes/Blue/images/shadow.png
  plugins/theme/themes/Blue/images/top-bottom.png
  plugins/theme/themes/Blue/init.js
  plugins/theme/themes/Blue/style.css
  plugins/theme/themes/MaterialDesign/style.css
Labels: bug, v5.0, Beta Feedback

#2724 Fix torrent deleted without confirmation
  js/common.js
  js/objects.js
  js/stable.js
  js/webui.js
Labels: bug, v5.0, Beta Feedback

#2727 Backport torrent delete confirmation
  js/webui.js
Labels: bug, v4.3

#2725 Adjust dialog window structure
  css/style.css
  js/common.js
  js/objects.js
  plugins/_task/_task.css
  plugins/bulk_magnet/bulk_magnet.css
  plugins/create/create.css
  plugins/create/konqueror.css
  plugins/datadir/datadir.css
  plugins/edit/edit.css
  plugins/extratio/extratio.css
  plugins/extratio/init.js
  plugins/extsearch/extsearch.css
  plugins/history/init.js
  plugins/rss/rss.css
  plugins/rssurlrewrite/rssurlrewrite.css
  plugins/theme/themes/Acid/plugins.css
  plugins/theme/themes/Acid/style.css
  plugins/theme/themes/Blue/style.css
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/plugins.css
  plugins/theme/themes/DarkBetter/style.css
  plugins/theme/themes/Excel/style.css
  plugins/theme/themes/MaterialDesign/images/dlg-rssurlrewrite.gif
  plugins/theme/themes/MaterialDesign/images/dlg-toolbars.gif
  plugins/theme/themes/MaterialDesign/plugins.css
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/images/dlg-rssurlrewrite.gif
  plugins/theme/themes/Oblivion/images/dlg-toolbars.gif
  plugins/theme/themes/Oblivion/plugins.css
  plugins/theme/themes/Oblivion/style.css
  plugins/unpack/unpack.css
Labels: bug, v5.0

#2732 Fix addPaneToStatusBar backward compatibility
  js/plugins.js
  plugins/cpuload/init.js
  plugins/diskspace/init.js
Labels: bug, v5.0

#2733 Fix task log copy formatting
  plugins/_task/_task.css
  plugins/_task/init.js
  plugins/_task/lang/cs.js
  plugins/_task/lang/da.js
  plugins/_task/lang/de.js
  plugins/_task/lang/el.js
  plugins/_task/lang/en.js
  plugins/_task/lang/es.js
  plugins/_task/lang/fi.js
  plugins/_task/lang/fr.js
  plugins/_task/lang/hu.js
  plugins/_task/lang/it.js
  plugins/_task/lang/ko.js
  plugins/_task/lang/lv.js
  plugins/_task/lang/nl.js
  plugins/_task/lang/no.js
  plugins/_task/lang/pl.js
  plugins/_task/lang/pt-br.js
  plugins/_task/lang/pt-pt.js
  plugins/_task/lang/ru.js
  plugins/_task/lang/sk.js
  plugins/_task/lang/sr.js
  plugins/_task/lang/sv.js
  plugins/_task/lang/tr.js
  plugins/_task/lang/uk.js
  plugins/_task/lang/vi.js
  plugins/_task/lang/zh-cn.js
  plugins/_task/lang/zh-tw.js
Labels: bug, enhancement, v5.0

#2736 MaterialDesign: update fonts
  plugins/theme/themes/MaterialDesign/font/4iCs6KVjbNBYlgoKcQ72j00.woff2
  plugins/theme/themes/MaterialDesign/font/4iCs6KVjbNBYlgoKcg72j00.woff2
  plugins/theme/themes/MaterialDesign/font/4iCs6KVjbNBYlgoKcw72j00.woff2
  plugins/theme/themes/MaterialDesign/font/4iCs6KVjbNBYlgoKew72j00.woff2
  plugins/theme/themes/MaterialDesign/font/4iCs6KVjbNBYlgoKfA72j00.woff2
  plugins/theme/themes/MaterialDesign/font/4iCs6KVjbNBYlgoKfw72.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmSU5fABc4EsA.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmSU5fBBc4.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmSU5fBxc4EsA.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmSU5fCBc4EsA.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmSU5fCRc4EsA.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmSU5fChc4EsA.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmSU5fCxc4EsA.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmWUlfABc4EsA.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmWUlfBBc4.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmWUlfBxc4EsA.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmWUlfCBc4EsA.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmWUlfCRc4EsA.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmWUlfChc4EsA.woff2
  plugins/theme/themes/MaterialDesign/font/KFOlCnqEu92Fr1MmWUlfCxc4EsA.woff2
  plugins/theme/themes/MaterialDesign/font/KFOmCnqEu92Fr1Mu4WxKOzY.woff2
  plugins/theme/themes/MaterialDesign/font/KFOmCnqEu92Fr1Mu4mxK.woff2
  plugins/theme/themes/MaterialDesign/font/KFOmCnqEu92Fr1Mu5mxKOzY.woff2
  plugins/theme/themes/MaterialDesign/font/KFOmCnqEu92Fr1Mu72xKOzY.woff2
  plugins/theme/themes/MaterialDesign/font/KFOmCnqEu92Fr1Mu7GxKOzY.woff2
  plugins/theme/themes/MaterialDesign/font/KFOmCnqEu92Fr1Mu7WxKOzY.woff2
  plugins/theme/themes/MaterialDesign/font/KFOmCnqEu92Fr1Mu7mxKOzY.woff2
  plugins/theme/themes/MaterialDesign/font/LICENSE.txt
  plugins/theme/themes/MaterialDesign/font/roboto-300.ttf
  plugins/theme/themes/MaterialDesign/font/roboto-400.ttf
  plugins/theme/themes/MaterialDesign/font/roboto-700.ttf
  plugins/theme/themes/MaterialDesign/font/ubuntu.woff
  plugins/theme/themes/MaterialDesign/plugins.css
  plugins/theme/themes/MaterialDesign/stable.css
  plugins/theme/themes/MaterialDesign/style.css
Labels: bug, enhancement, v5.1

#2746 screenshots plugin: take screenshot with correct aspect ratio from anamorphic video
  plugins/screenshots/action.php
  plugins/screenshots/conf.php
Labels: bug, enhancement, v5.1

#2747 rss plugin: add "Regular Expression Example"
  plugins/rss/init.js
  plugins/rss/lang/cs.js
  plugins/rss/lang/da.js
  plugins/rss/lang/de.js
  plugins/rss/lang/el.js
  plugins/rss/lang/en.js
  plugins/rss/lang/es.js
  plugins/rss/lang/fi.js
  plugins/rss/lang/fr.js
  plugins/rss/lang/hu.js
  plugins/rss/lang/it.js
  plugins/rss/lang/ko.js
  plugins/rss/lang/lv.js
  plugins/rss/lang/nl.js
  plugins/rss/lang/no.js
  plugins/rss/lang/pl.js
  plugins/rss/lang/pt-br.js
  plugins/rss/lang/pt-pt.js
  plugins/rss/lang/ru.js
  plugins/rss/lang/sk.js
  plugins/rss/lang/sr.js
  plugins/rss/lang/sv.js
  plugins/rss/lang/tr.js
  plugins/rss/lang/uk.js
  plugins/rss/lang/vi.js
  plugins/rss/lang/zh-cn.js
  plugins/rss/lang/zh-tw.js
Labels: enhancement, v5.1

#2749 Limit context menu on mobile
  css/style.css
  index.html
  js/plugins.js
  js/webui.js
  plugins/bulk_magnet/init.js
  plugins/extratio/init.js
  plugins/rssurlrewrite/init.js
Labels: enhancement, v5.1

#2750 Persistent add and create torrent options
  css/style.css
  js/content.js
  js/webui.js
  php/cache.php
  plugins/create/action.php
  plugins/create/init.js
  plugins/theme/themes/Acid/style.css
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/style.css
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/style.css
Labels: enhancement, v5.1

#2761 Fix dialog window text input unfocusable
  css/category-panel.css
  index.html
  js/objects.js
  js/webui.js
Labels: bug, enhancement, v5.1

#2760 Fix RSS URL rule error
  plugins/rssurlrewrite/init.js
Labels: bug, v5.1

#2764 Allow wrapping in button groups on top toolbar
  index.html
  js/content.js
  plugins/_getdir/_getdir.css
Labels: bug, enhancement, Beta Feedback, v5.1

#2767 Define theme colors for dropdown menus
  css/style.css
  js/content.js
  js/plugins.js
  plugins/create/init.js
  plugins/datadir/init.js
  plugins/theme/themes/Acid/style.css
  plugins/theme/themes/Blue/style.css
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/style.css
  plugins/theme/themes/Excel/style.css
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/style.css
Labels: enhancement, Beta Feedback, v5.1

#2768 Read dir content without trailing slash
  plugins/_getdir/init.js
  plugins/_getdir/listdir.php
Labels: bug, Beta Feedback, v5.1

#2772 Prevent collapse menu from pushing content down
  css/style.css
  index.html
  js/content.js
  plugins/theme/themes/Acid/style.css
  plugins/theme/themes/Blue/style.css
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/style.css
  plugins/theme/themes/Excel/style.css
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/style.css
Labels: bug, enhancement, v5.1
