Repository Novik/ruTorrent, pull requests merged in 2024-11, with the labels that each got.

#2773 Adjust task console log layout
  css/style.css
  plugins/_task/_task.css
  plugins/_task/init.js
  plugins/screenshots/init.js
  plugins/screenshots/screenshots.css
  plugins/spectrogram/init.js
Labels: bug, enhancement, v5.1

#2781 fix mobile dialog window sizing issue
  css/style.css
Labels: bug, v5.1

#2780 Use CSS to indicate the importance of whitespace rather than replacing with nbsp's
  plugins/_getdir/_getdir.css
  plugins/_getdir/init.js
Labels: bug, v5.1

#2783 Convert recentTrackers->last_used to an array
  plugins/create/action.php
  plugins/create/init.js
Labels: bug, v5.1

#2786 update Polish translation
  lang/pl.js
  plugins/_getdir/lang/pl.js
  plugins/_task/lang/pl.js
  plugins/extratio/lang/pl.js
  plugins/rss/lang/pl.js
Labels: v5.1

#2787 fix default group/channel setting
  plugins/ratio/init.js
  plugins/throttle/init.js
Labels: bug, v5.1

#2792 fix settings background
  css/style.css
  plugins/theme/themes/Acid/style.css
Labels: bug, v5.1

#2797 Fix create torrent from empty path
  .gitignore
  .vscode/settings.json
  plugins/create/action.php
  plugins/create/init.js
Labels: bug, v5.1

#2804 Fix torrent deleted without confirmation
  js/common.js
  js/objects.js
  js/stable.js
  js/webui.js
Labels: v5.2

#2806 filedrop plugin: support dropped links
  plugins/filedrop/init.js
Labels: enhancement, v5.2

#2796 ENV configuration in config.php
  conf/config.php
Labels: enhancement, v5.2

#2807 Fix typo in resizeLeft function
  js/webui.js
Labels: bug, v5.1

#2805 Remove drag mask object
  css/style.css
  index.html
  js/content.js
  js/objects.js
  js/webui.js
  lang/bn.js
  lang/cs.js
  lang/da.js
  lang/de.js
  lang/el.js
  lang/en.js
  lang/es.js
  lang/fi.js
  lang/fr.js
  lang/hu.js
  lang/it.js
  lang/ko.js
  lang/lv.js
  lang/nl.js
  lang/no.js
  lang/pl.js
  lang/pt-br.js
  lang/pt-pt.js
  lang/ru.js
  lang/sk.js
  lang/sr.js
  lang/sv.js
  lang/tr.js
  lang/uk.js
  lang/vi.js
  lang/zh-cn.js
  lang/zh-tw.js
  plugins/_getdir/init.js
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/style.css
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/style.css
Labels: enhancement, v5.2

#2809 Use bootstrap dropdown on recent trackers
  css/style.css
  js/plugins.js
  plugins/create/action.php
  plugins/create/create.css
  plugins/create/init.js
Labels: bug, enhancement, v5.2

#2811 Fix create torrent announce group
  plugins/create/action.php
  plugins/create/init.js
Labels: bug, v5.1
