Repository Novik/ruTorrent, pull requests merged in 2024-07, with the labels that each got.

#2685 Make throttle an optional dependency for extratio
  plugins/extratio/init.js
  plugins/extratio/plugin.info
Labels: enhancement, v4.4

#2688 Update lang files for check port and create plugin
  plugins/check_port/lang/cs.js
  plugins/check_port/lang/da.js
  plugins/check_port/lang/de.js
  plugins/check_port/lang/el.js
  plugins/check_port/lang/en.js
  plugins/check_port/lang/es.js
  plugins/check_port/lang/fi.js
  plugins/check_port/lang/fr.js
  plugins/check_port/lang/hu.js
  plugins/check_port/lang/it.js
  plugins/check_port/lang/ko.js
  plugins/check_port/lang/lv.js
  plugins/check_port/lang/nl.js
  plugins/check_port/lang/no.js
  plugins/check_port/lang/pl.js
  plugins/check_port/lang/pt-br.js
  plugins/check_port/lang/pt-pt.js
  plugins/check_port/lang/ru.js
  plugins/check_port/lang/sk.js
  plugins/check_port/lang/sr.js
  plugins/check_port/lang/sv.js
  plugins/check_port/lang/tr.js
  plugins/check_port/lang/uk.js
  plugins/check_port/lang/vi.js
  plugins/check_port/lang/zh-cn.js
  plugins/check_port/lang/zh-tw.js
  plugins/create/lang/cs.js
  plugins/create/lang/da.js
  plugins/create/lang/de.js
  plugins/create/lang/el.js
  plugins/create/lang/en.js
  plugins/create/lang/es.js
  plugins/create/lang/fi.js
  plugins/create/lang/fr.js
  plugins/create/lang/hu.js
  plugins/create/lang/it.js
  plugins/create/lang/ko.js
  plugins/create/lang/lv.js
  plugins/create/lang/nl.js
  plugins/create/lang/no.js
  plugins/create/lang/pl.js
  plugins/create/lang/pt-br.js
  plugins/create/lang/pt-pt.js
  plugins/create/lang/ru.js
  plugins/create/lang/sk.js
  plugins/create/lang/sr.js
  plugins/create/lang/sv.js
  plugins/create/lang/tr.js
  plugins/create/lang/uk.js
  plugins/create/lang/vi.js
  plugins/create/lang/zh-cn.js
  plugins/create/lang/zh-tw.js
Labels: enhancement, v4.4

#2690 Make responsive status bar
  css/style.css
  index.html
  js/plugins.js
  plugins/check_port/check_port.css
  plugins/check_port/init.js
  plugins/check_port/lang/cs.js
  plugins/check_port/lang/da.js
  plugins/check_port/lang/de.js
  plugins/check_port/lang/el.js
  plugins/check_port/lang/en.js
  plugins/check_port/lang/es.js
  plugins/check_port/lang/fi.js
  plugins/check_port/lang/fr.js
  plugins/check_port/lang/hu.js
  plugins/check_port/lang/it.js
  plugins/check_port/lang/ko.js
  plugins/check_port/lang/lv.js
  plugins/check_port/lang/nl.js
  plugins/check_port/lang/no.js
  plugins/check_port/lang/pl.js
  plugins/check_port/lang/pt-br.js
  plugins/check_port/lang/pt-pt.js
  plugins/check_port/lang/ru.js
  plugins/check_port/lang/sk.js
  plugins/check_port/lang/sr.js
  plugins/check_port/lang/sv.js
  plugins/check_port/lang/tr.js
  plugins/check_port/lang/uk.js
  plugins/check_port/lang/vi.js
  plugins/check_port/lang/zh-cn.js
  plugins/check_port/lang/zh-tw.js
  plugins/cpuload/cpuload.css
  plugins/cpuload/init.js
  plugins/diskspace/diskspace.css
  plugins/diskspace/init.js
  plugins/theme/themes/DarkBetter/plugins.css
Labels: enhancement, v4.4

#2692 Apply flex layout to save-to dialog window
  css/style.css
  plugins/_getdir/_getdir.css
  plugins/_getdir/init.js
  plugins/datadir/datadir.css
  plugins/datadir/init.js
Labels: enhancement, v4.4

#2694 Apply flex layout to edit dialog window
  css/style.css
  plugins/edit/edit.css
  plugins/edit/init.js
Labels: enhancement, v4.4

#2695 Migrate from grid-only to full Bootstrap
  css/bootstrap-grid.min.css
  css/bootstrap.min.css
  css/stable.css
  css/style.css
  index.html
  js/content.js
  js/stable.js
  plugins/diskspace/diskspace.css
Labels: bug, enhancement, v4.4

#2696 Add a responsive top menu
  css/style.css
  index.html
  js/bootstrap.bundle.min.js
  js/content.js
  js/plugins.js
  plugins/create/create.css
  plugins/extsearch/extsearch.css
  plugins/extsearch/init.js
  plugins/theme/themes/Acid/style.css
  plugins/theme/themes/Blue/style.css
  plugins/theme/themes/Dark/style.css
  plugins/theme/themes/DarkBetter/plugins.css
  plugins/theme/themes/DarkBetter/style.css
  plugins/theme/themes/Excel/style.css
  plugins/theme/themes/MaterialDesign/style.css
  plugins/theme/themes/Oblivion/style.css
Labels: enhancement, v4.4

#2697 Update/create PT-pt translations
  lang/pt-pt.js
  plugins/_task/lang/pt-pt.js
  plugins/dump/lang/pt-pt.js
  plugins/extratio/lang/pt-pt.js
Labels: v4.4
